eds_apis:
  Maxson:
    url: "http://172.19.4.127:43084/api/v1/"
    username: "admin"
    password: ""
  
  WWTF: # Stiles
    url: "http://172.19.4.128:43084/api/v1/"
    username: "admin"
    password: ""
    
  Maxson-SOAP:
    url: "http://172.19.4.127:43080/api/eds.wsl"
    username: "admin"
    password: ""
    
  Stiles-SOAP:
    url: "http://172.19.4.127:43080/api/eds.wsl"
    username: "admin"
    password: ""

contractor_apis:
  RJN:
    url: "https://rjn-clarity-api.com/v1/clarity/"
    client_id: "OuREElQ2"
    password: "0.k2h6i19utie0.nzom0vbg020."