eds_apis:
  WWTF:
    url: "http://127.0.0.1:43084/api/v1/"
    username: "admin"
    password: ""
third_party_api:
  url: "https://really_special_website.com/api/v1/"
  username: "admin"
  password: ""